services:
  redis-stack:
    image: redis/redis-stack:7.4.0-v2
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_stack_data:/data

volumes:
  redis_stack_data: